name: rickandmorty
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  json_annotation: ^4.4.0
  build_runner: ^2.1.10
  dio: ^4.0.6
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  freezed_annotation: ^2.0.1
  json_serializable: ^6.1.6
  pull_to_refresh: ^2.0.0
  flutter_easyrefresh: ^2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/image/rick.jpg
  - assets/image/morty.png
  - assets/image/1.png
  - assets/image/2.png
  - assets/image/3.png
  - assets/image/4.png
  - assets/image/5.png
#  - assets/image/6.png
  - assets/image/7.png
  - assets/image/8.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
